const std = @import("std");
const Allocator = std.mem.Allocator;
const ir = @import("ir.zig");

// Import our modular components
const helpers = @import("x64/helpers.zig");
const instruction_gen = @import("x64/instruction_gen.zig");

// Re-export for external use
pub const StackLayout = helpers.StackLayout;
const GenContext = helpers.GenContext;
const Patterns = helpers.Patterns;

/// x64 Assembly Generator
/// Clean orchestrator that delegates to specialized modules
pub const X64Generator = struct {
    allocator: Allocator,
    output: std.ArrayList(u8),
    label_counter: u32,
    current_layout: ?StackLayout,
    current_module: ?*const ir.Module,

    pub fn init(allocator: Allocator) !X64Generator {
        const empty = try allocator.alloc(u8, 0);
        return .{
            .allocator = allocator,
            .output = std.ArrayList(u8).fromOwnedSlice(empty),
            .label_counter = 0,
            .current_layout = null,
            .current_module = null,
        };
    }

    pub fn deinit(self: *X64Generator) void {
        self.output.deinit(self.allocator);
        if (self.current_layout) |*layout| {
            layout.deinit();
        }
    }

    /// Generate x64 assembly from IR module
    pub fn generateFromIR(self: *X64Generator, module: *const ir.Module) !void {
        self.current_module = module;

        try self.emitHeader();
        try self.emitDataSection(module);
        try self.emitTextSection(module);
        try self.emitMainWrapper(module);

        self.current_module = null;
    }

    fn emitHeader(self: *X64Generator) !void {
        try self.output.writer(self.allocator).print(".intel_syntax noprefix\n", .{});
        try self.output.writer(self.allocator).print("\n", .{});
    }

    fn emitDataSection(self: *X64Generator, module: *const ir.Module) !void {
        const has_strings = module.string_table.items.len > 0;
        const has_globals = module.globals.items.len > 0;

        if (!has_strings and !has_globals) return;

        // Emit read-only data (strings)
        if (has_strings) {
            try self.output.writer(self.allocator).print(".section .rodata\n", .{});
            for (module.string_table.items, 0..) |str, i| {
                try self.output.writer(self.allocator).print(".str{d}:\n", .{i});
                try self.output.writer(self.allocator).print("    .string \"{s}\"\n", .{str});
            }
            try self.output.writer(self.allocator).print("\n", .{});
        }

        // Emit global variables
        if (has_globals) {
            try self.output.writer(self.allocator).print(".section .data\n", .{});
            for (module.globals.items) |global| {
                try self.output.writer(self.allocator).print(".globl {s}\n", .{global.name});
                try self.output.writer(self.allocator).print("{s}:\n", .{global.name});

                // Emit initializer or zero
                if (global.init_value) |init_val| {
                    switch (init_val) {
                        .constant => |c| switch (c) {
                            .int => |val| try self.output.writer(self.allocator).print("    .quad {d}\n", .{val}),
                            .float => |val| {
                                // Convert float to hex representation for assembly
                                const int_bits: u64 = @bitCast(val);
                                try self.output.writer(self.allocator).print("    .quad 0x{x}\n", .{int_bits});
                            },
                            .bool => |val| try self.output.writer(self.allocator).print("    .quad {d}\n", .{@as(i64, if (val) 1 else 0)}),
                        },
                        else => {
                            // Fallback to zero initialization for complex cases
                            try self.output.writer(self.allocator).print("    .quad 0\n", .{});
                        },
                    }
                } else {
                    // No initializer - zero initialize
                    try self.output.writer(self.allocator).print("    .quad 0\n", .{});
                }
            }
            try self.output.writer(self.allocator).print("\n", .{});
        }
    }

    fn emitTextSection(self: *X64Generator, module: *const ir.Module) !void {
        try self.output.writer(self.allocator).print(".section .text\n", .{});

        for (module.functions.items) |*func| {
            try self.generateFunction(func);
        }
    }

    fn emitMainWrapper(self: *X64Generator, module: *const ir.Module) !void {
        _ = self;
        _ = module;
        // Note: C's main() function is now generated by the IR builder
        // (see buildCMainFunction in ir_builder.zig)
    }

    fn generateFunction(self: *X64Generator, func: *const ir.Function) !void {
        // Calculate stack layout
        var layout = try self.calculateStackLayout(func);
        defer layout.deinit();
        self.current_layout = layout;

        // Create generation context
        var ctx = GenContext{
            .allocator = self.allocator,
            .output = &self.output,
            .current_layout = &layout,
            .current_module = self.current_module,
        };

        // Emit function prologue
        try Patterns.emitFunctionPrologue(&ctx, func.name, layout.total_size);

        // Generate code for each basic block
        for (func.blocks.items) |*block| {
            try self.generateBasicBlock(&ctx, block, func.name);
        }

        // Function epilogue (fallthrough case)
        try ctx.emit(".Lend_{s}:\n", .{func.name});
        try Patterns.emitFunctionEpilogue(&ctx);
        try ctx.emit("\n", .{});

        self.current_layout = null;
    }

    fn generateBasicBlock(self: *X64Generator, ctx: *GenContext, block: *const ir.BasicBlock, func_name: []const u8) !void {
        _ = self;
        try ctx.emit(".L{s}_block{d}:\n", .{ func_name, block.id });

        var param_idx: u32 = 0;
        for (block.instructions.items) |*instr| {
            // Track parameter index for param instructions
            if (instr.opcode == .param) {
                try generateInstructionWithParamIdx(ctx, instr, param_idx);
                param_idx += 1;
            } else {
                try generateInstruction(ctx, instr);
            }
        }
    }

    /// Calculate stack layout for a function
    fn calculateStackLayout(self: *X64Generator, func: *const ir.Function) !StackLayout {
        var layout = StackLayout.init(self.allocator);
        errdefer layout.deinit();

        var offset: i64 = 8; // Start at 8 (first slot after saved RBP)

        // Collect all variables and temps used in the function
        var vars = std.StringHashMap(void).init(self.allocator);
        defer vars.deinit();
        var temps = std.AutoHashMap(u32, void).init(self.allocator);
        defer temps.deinit();

        // Scan all instructions to find variables and temps
        for (func.blocks.items) |*block| {
            for (block.instructions.items) |*instr| {
                try collectOperandVars(instr.dest, &vars, &temps);
                try collectOperandVars(instr.src1, &vars, &temps);
                try collectOperandVars(instr.src2, &vars, &temps);
            }
        }

        // Assign offsets to variables
        var var_iter = vars.keyIterator();
        while (var_iter.next()) |var_name| {
            try layout.var_offsets.put(var_name.*, offset);
            offset += 8;
        }

        // Assign offsets to temps
        var temp_iter = temps.keyIterator();
        while (temp_iter.next()) |temp_id| {
            try layout.temp_offsets.put(temp_id.*, offset);
            offset += 8;
        }

        layout.total_size = @intCast(offset - 8);

        // Align to 16 bytes (System V ABI requirement)
        if (layout.total_size % 16 != 0) {
            layout.total_size = ((layout.total_size / 16) + 1) * 16;
        }

        return layout;
    }

    fn collectOperandVars(operand: ir.Operand, vars: *std.StringHashMap(void), temps: *std.AutoHashMap(u32, void)) !void {
        switch (operand) {
            .variable => |v| try vars.put(v, {}),
            .temp => |t| try temps.put(t, {}),
            else => {},
        }
    }

    pub fn getOutput(self: *X64Generator) []const u8 {
        return self.output.items;
    }
};

/// Main instruction dispatcher - delegates to category-specific generators
fn generateInstruction(ctx: *GenContext, instr: *const ir.Instruction) !void {
    switch (instr.opcode) {
        // Control flow
        .ret => try instruction_gen.ControlFlow.genRet(ctx),
        .ret_val => try instruction_gen.ControlFlow.genRetVal(ctx),
        .label => try instruction_gen.ControlFlow.genLabel(ctx, instr),
        .jump => try instruction_gen.ControlFlow.genJump(ctx, instr),
        .jump_if_zero => try instruction_gen.ControlFlow.genJumpIfZero(ctx, instr),
        .jump_if_not_zero => try instruction_gen.ControlFlow.genJumpIfNotZero(ctx, instr),

        // Memory/Data movement
        .load_const => try instruction_gen.Memory.genLoadConst(ctx, instr),
        .load_var => try instruction_gen.Memory.genLoadVar(ctx, instr),
        .store_var => try instruction_gen.Memory.genStoreVar(ctx, instr),
        .move => try instruction_gen.Memory.genMove(ctx, instr),
        .alloc_local => try instruction_gen.Memory.genAllocLocal(ctx),
        .load_addr => try instruction_gen.Memory.genLoadAddr(ctx, instr),
        .load_ptr => try instruction_gen.Memory.genLoadPtr(ctx, instr),
        .store_ptr => try instruction_gen.Memory.genStorePtr(ctx, instr),
        .param => unreachable, // Should use generateInstructionWithParamIdx

        // Arithmetic
        .add => try instruction_gen.Arithmetic.genAdd(ctx, instr),
        .sub => try instruction_gen.Arithmetic.genSub(ctx, instr),
        .mul => try instruction_gen.Arithmetic.genMul(ctx, instr),
        .div => try instruction_gen.Arithmetic.genDiv(ctx, instr),
        .mod => try instruction_gen.Arithmetic.genMod(ctx, instr),
        .neg => try instruction_gen.Arithmetic.genNeg(ctx, instr),

        // Bitwise
        .bit_and => try instruction_gen.Bitwise.genBitAnd(ctx, instr),
        .bit_or => try instruction_gen.Bitwise.genBitOr(ctx, instr),
        .bit_xor => try instruction_gen.Bitwise.genBitXor(ctx, instr),
        .bit_not => try instruction_gen.Bitwise.genBitNot(ctx, instr),
        .shl => try instruction_gen.Bitwise.genShl(ctx, instr),
        .shr => try instruction_gen.Bitwise.genShr(ctx, instr),

        // Logical
        .log_and => try instruction_gen.Logical.genLogAnd(ctx, instr),
        .log_or => try instruction_gen.Logical.genLogOr(ctx, instr),
        .log_xor => try instruction_gen.Logical.genLogXor(ctx, instr),
        .log_not => try instruction_gen.Logical.genLogNot(ctx, instr),

        // Comparison
        .cmp_eq => try instruction_gen.Comparison.genCmpEq(ctx, instr),
        .cmp_ne => try instruction_gen.Comparison.genCmpNe(ctx, instr),
        .cmp_lt => try instruction_gen.Comparison.genCmpLt(ctx, instr),
        .cmp_le => try instruction_gen.Comparison.genCmpLe(ctx, instr),
        .cmp_gt => try instruction_gen.Comparison.genCmpGt(ctx, instr),
        .cmp_ge => try instruction_gen.Comparison.genCmpGe(ctx, instr),

        // Functions
        .call => try instruction_gen.Functions.genCall(ctx, instr),
        .print => try instruction_gen.Functions.genPrint(ctx, instr),
    }
}

/// Instruction dispatcher for param instructions (needs parameter index)
fn generateInstructionWithParamIdx(ctx: *GenContext, instr: *const ir.Instruction, param_idx: u32) !void {
    switch (instr.opcode) {
        .param => try instruction_gen.Memory.genParam(ctx, instr, param_idx),
        else => try generateInstruction(ctx, instr),
    }
}
