const std = @import("std");
const lib = @import("holycross");
const Linker = lib.linker.Linker;
const GlobalAllocator = lib.allocator;

/// hcl - HolyC Linker
/// Standalone linker for HolyC object files
pub fn main(init: std.process.Init) !void {
    var gpa = GlobalAllocator.init();
    defer GlobalAllocator.deinit(&gpa);
    
    const allocator = GlobalAllocator.allocator(&gpa);
    
    // Create arena for args allocation
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    
    // Get command line arguments
    const args = try init.minimal.args.toSlice(arena.allocator());
    
    // Parse arguments
    if (args.len < 2) {
        printUsage(args[0]);
        return;
    }
    
    const empty_input_files = try arena.allocator().alloc([]const u8, 0);
    var input_files = std.ArrayList([]const u8).fromOwnedSlice(empty_input_files);
    var output_file: []const u8 = "a.out";
    var entry_point: ?[]const u8 = null;
    
    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        const arg = args[i];
        
        if (std.mem.eql(u8, arg, "--help") or std.mem.eql(u8, arg, "-h")) {
            printUsage(args[0]);
            return;
        } else if (std.mem.eql(u8, arg, "--version") or std.mem.eql(u8, arg, "-v")) {
            printVersion();
            return;
        } else if (std.mem.eql(u8, arg, "-o")) {
            i += 1;
            if (i < args.len) {
                output_file = args[i];
            } else {
                std.debug.print("Error: -o flag requires an argument\n", .{});
                return error.MissingOutputFile;
            }
        } else if (std.mem.eql(u8, arg, "-e")) {
            i += 1;
            if (i < args.len) {
                entry_point = args[i];
            } else {
                std.debug.print("Error: -e flag requires an argument\n", .{});
                return error.MissingEntryPoint;
            }
        } else if (std.mem.startsWith(u8, arg, "-")) {
            std.debug.print("Error: Unknown flag '{s}'\n", .{arg});
            return error.UnknownFlag;
        } else {
            try input_files.append(arena.allocator(), arg);
        }
    }
    
    if (input_files.items.len == 0) {
        std.debug.print("Error: No input files specified\n", .{});
        printUsage(args[0]);
        return error.NoInputFiles;
    }
    
    // Initialize linker
    var linker = try Linker.init(allocator);
    defer linker.deinit();
    
    // Set entry point if specified
    if (entry_point) |ep| {
        linker.setEntryPoint(ep);
    }
    
    // Read all input files
    const cwd = std.Io.Dir.cwd();
    for (input_files.items) |file_path| {
        const data = cwd.readFileAlloc(init.io, file_path, allocator, std.Io.Limit.limited(100 * 1024 * 1024)) catch |err| {
            std.debug.print("Error reading '{s}': {}\n", .{ file_path, err });
            return err;
        };
        // Don't free - linker takes ownership
        try linker.addObject(data);
    }
    
    // Link!
    try linker.link(output_file, init.io);
}

fn printVersion() void {
    std.debug.print("hcl v0.1.0 - HolyC Linker\n", .{});
    std.debug.print("Part of the HolyCross toolchain\n", .{});
    std.debug.print("Target: x64 (AMD64)\n", .{});
}

fn printUsage(program_name: []const u8) void {
    std.debug.print("Usage: {s} [options] <input.o> [input2.o ...]\n", .{program_name});
    std.debug.print("\n", .{});
    std.debug.print("HolyC Linker - Link object files into executables\n", .{});
    std.debug.print("\n", .{});
    std.debug.print("Options:\n", .{});
    std.debug.print("  -o <file>          Write output to <file> (default: a.out)\n", .{});
    std.debug.print("  -e <symbol>        Set entry point symbol (default: _start)\n", .{});
    std.debug.print("  -h, --help         Show this help message\n", .{});
    std.debug.print("  -v, --version      Show version information\n", .{});
    std.debug.print("\n", .{});
    std.debug.print("Examples:\n", .{});
    std.debug.print("  {s} main.o -o program\n", .{program_name});
    std.debug.print("  {s} foo.o bar.o baz.o -o app\n", .{program_name});
    std.debug.print("  {s} test.o -e main -o test\n", .{program_name});
    std.debug.print("\n", .{});
    std.debug.print("Supported Input:\n", .{});
    std.debug.print("  - ELF64 relocatable object files (.o)\n", .{});
    std.debug.print("  - Generated by hcas or compatible assemblers\n", .{});
}
